# Generated by Django 5.0 on 2024-03-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='formdata',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='formdata',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterModelTable(
            name='formdata',
            table='Persons',
        ),
    ]
